-- ═══════════════════════════════════════════════════════════════════════════
-- HAMRO RENT — Manual Security SQL
-- Run this in Supabase SQL Editor if the migration hasn't been applied yet.
-- This is identical to supabase/migrations/20260611000001_security_hardening.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- See supabase/migrations/20260611000001_security_hardening.sql for the full script.
-- Copy-paste that file into Supabase → SQL Editor → New query → Run.
