/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as DemoTenantsRouteImport } from './routes/demo/tenants'
import { Route as DemoDashboardRouteImport } from './routes/demo/dashboard'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillsRouteImport } from './routes/_authenticated/bills'
import { Route as DemoBillsNewRouteImport } from './routes/demo/bills.new'
import { Route as AuthenticatedTenantsTenantIdRouteImport } from './routes/_authenticated/tenants.$tenantId'
import { Route as AuthenticatedBillsNewRouteImport } from './routes/_authenticated/bills.new'
import { Route as AuthenticatedBillsBillIdRouteImport } from './routes/_authenticated/bills.$billId'
import { Route as ApiPublicBillTokenRouteImport } from './routes/api/public/bill.$token'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTenantsRoute = DemoTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => DemoRoute,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DemoRoute,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillsRoute = AuthenticatedBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DemoBillsNewRoute = DemoBillsNewRouteImport.update({
  id: '/bills/new',
  path: '/bills/new',
  getParentRoute: () => DemoRoute,
} as any)
const AuthenticatedTenantsTenantIdRoute =
  AuthenticatedTenantsTenantIdRouteImport.update({
    id: '/$tenantId',
    path: '/$tenantId',
    getParentRoute: () => AuthenticatedTenantsRoute,
  } as any)
const AuthenticatedBillsNewRoute = AuthenticatedBillsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedBillsRoute,
} as any)
const AuthenticatedBillsBillIdRoute =
  AuthenticatedBillsBillIdRouteImport.update({
    id: '/$billId',
    path: '/$billId',
    getParentRoute: () => AuthenticatedBillsRoute,
  } as any)
const ApiPublicBillTokenRoute = ApiPublicBillTokenRouteImport.update({
  id: '/api/public/bill/$token',
  path: '/api/public/bill/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/bills': typeof AuthenticatedBillsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/tenants': typeof DemoTenantsRoute
  '/share/$token': typeof ShareTokenRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/bills/new': typeof AuthenticatedBillsNewRoute
  '/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRoute
  '/demo/bills/new': typeof DemoBillsNewRoute
  '/api/public/bill/$token': typeof ApiPublicBillTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/bills': typeof AuthenticatedBillsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/tenants': typeof DemoTenantsRoute
  '/share/$token': typeof ShareTokenRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/bills/new': typeof AuthenticatedBillsNewRoute
  '/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRoute
  '/demo/bills/new': typeof DemoBillsNewRoute
  '/api/public/bill/$token': typeof ApiPublicBillTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/_authenticated/bills': typeof AuthenticatedBillsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/tenants': typeof DemoTenantsRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authenticated/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/_authenticated/bills/new': typeof AuthenticatedBillsNewRoute
  '/_authenticated/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRoute
  '/demo/bills/new': typeof DemoBillsNewRoute
  '/api/public/bill/$token': typeof ApiPublicBillTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/home'
    | '/login'
    | '/bills'
    | '/dashboard'
    | '/export'
    | '/profile'
    | '/settings'
    | '/tenants'
    | '/demo/dashboard'
    | '/demo/tenants'
    | '/share/$token'
    | '/bills/$billId'
    | '/bills/new'
    | '/tenants/$tenantId'
    | '/demo/bills/new'
    | '/api/public/bill/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/home'
    | '/login'
    | '/bills'
    | '/dashboard'
    | '/export'
    | '/profile'
    | '/settings'
    | '/tenants'
    | '/demo/dashboard'
    | '/demo/tenants'
    | '/share/$token'
    | '/bills/$billId'
    | '/bills/new'
    | '/tenants/$tenantId'
    | '/demo/bills/new'
    | '/api/public/bill/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/demo'
    | '/home'
    | '/login'
    | '/_authenticated/bills'
    | '/_authenticated/dashboard'
    | '/_authenticated/export'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/tenants'
    | '/demo/dashboard'
    | '/demo/tenants'
    | '/share/$token'
    | '/_authenticated/bills/$billId'
    | '/_authenticated/bills/new'
    | '/_authenticated/tenants/$tenantId'
    | '/demo/bills/new'
    | '/api/public/bill/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiPublicBillTokenRoute: typeof ApiPublicBillTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tenants': {
      id: '/demo/tenants'
      path: '/tenants'
      fullPath: '/demo/tenants'
      preLoaderRoute: typeof DemoTenantsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/dashboard': {
      id: '/demo/dashboard'
      path: '/dashboard'
      fullPath: '/demo/dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof DemoRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills': {
      id: '/_authenticated/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AuthenticatedBillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/demo/bills/new': {
      id: '/demo/bills/new'
      path: '/bills/new'
      fullPath: '/demo/bills/new'
      preLoaderRoute: typeof DemoBillsNewRouteImport
      parentRoute: typeof DemoRoute
    }
    '/_authenticated/tenants/$tenantId': {
      id: '/_authenticated/tenants/$tenantId'
      path: '/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdRouteImport
      parentRoute: typeof AuthenticatedTenantsRoute
    }
    '/_authenticated/bills/new': {
      id: '/_authenticated/bills/new'
      path: '/new'
      fullPath: '/bills/new'
      preLoaderRoute: typeof AuthenticatedBillsNewRouteImport
      parentRoute: typeof AuthenticatedBillsRoute
    }
    '/_authenticated/bills/$billId': {
      id: '/_authenticated/bills/$billId'
      path: '/$billId'
      fullPath: '/bills/$billId'
      preLoaderRoute: typeof AuthenticatedBillsBillIdRouteImport
      parentRoute: typeof AuthenticatedBillsRoute
    }
    '/api/public/bill/$token': {
      id: '/api/public/bill/$token'
      path: '/api/public/bill/$token'
      fullPath: '/api/public/bill/$token'
      preLoaderRoute: typeof ApiPublicBillTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedBillsRouteChildren {
  AuthenticatedBillsBillIdRoute: typeof AuthenticatedBillsBillIdRoute
  AuthenticatedBillsNewRoute: typeof AuthenticatedBillsNewRoute
}

const AuthenticatedBillsRouteChildren: AuthenticatedBillsRouteChildren = {
  AuthenticatedBillsBillIdRoute: AuthenticatedBillsBillIdRoute,
  AuthenticatedBillsNewRoute: AuthenticatedBillsNewRoute,
}

const AuthenticatedBillsRouteWithChildren =
  AuthenticatedBillsRoute._addFileChildren(AuthenticatedBillsRouteChildren)

interface AuthenticatedTenantsRouteChildren {
  AuthenticatedTenantsTenantIdRoute: typeof AuthenticatedTenantsTenantIdRoute
}

const AuthenticatedTenantsRouteChildren: AuthenticatedTenantsRouteChildren = {
  AuthenticatedTenantsTenantIdRoute: AuthenticatedTenantsTenantIdRoute,
}

const AuthenticatedTenantsRouteWithChildren =
  AuthenticatedTenantsRoute._addFileChildren(AuthenticatedTenantsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBillsRoute: typeof AuthenticatedBillsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillsRoute: AuthenticatedBillsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DemoRouteChildren {
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoTenantsRoute: typeof DemoTenantsRoute
  DemoBillsNewRoute: typeof DemoBillsNewRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoDashboardRoute: DemoDashboardRoute,
  DemoTenantsRoute: DemoTenantsRoute,
  DemoBillsNewRoute: DemoBillsNewRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiPublicBillTokenRoute: ApiPublicBillTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
